#pragma once
#define VOIDTO_PINT_RESOLVE(input)		static_cast<int*>(input)
#define VOIDTO_PDOUBLE_RESOLVE(input)	static_cast<double*>(input)
#define VOIDTO_PCHAR_RESOLVE(input)		static_cast<char*>(input)
#define VOIDTO_PUCHAR_RESOLVE(input)	static_cast<unsigned char*>(input)
#define VOIDTO_PLONG_RESOLVE(input)		static_cast<long*>(input)
#define VOIDTO_PULONG_RESOLVE(input)	static_cast<unsigned long*>(input)
#define VOIDTO_INT_RESOLVE(input)		*VOIDTO_PINT_RESOLVE(input)
#define VOIDTO_DOUBLE_RESOLVE(input)	*VOIDTO_PDOUBLE_RESOLVE(input)
#define VOIDTO_CHAR_RESOLVE(input)		*VOIDTO_PCHAR_RESOLVE(input)
#define VOIDTO_UCHAR_RESOLVE(input)		*VOIDTO_PUCHAR_RESOLVE(input)
#define VOIDTO_LONG_RESOLVE(input)		*VOIDTO_PLONG_RESOLVE(input)
#define VOIDTO_ULONG_RESOLVE(input)		*VOIDTO_PULONG_RESOLVE(input)
#define VOIDTO_STRING_RESOLVE(input)	 static_cast<const char*>(input)